spring:
  application:
    name: Event Linker
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.format_sql : true
      hibernate.hibernate.dialect : org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:file:.env[.properties]
logging:
  level:
    org.springframework.security : trace
    org.springframework.kafka : trace